spring.application.name=SB16-SpringBoot-JPA-MovieAssignment
server.port=9998

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/mycapgdb
spring.datasource.username=root
spring.datasource.password=admin123